### ISSUE TITLE
Direct Upload returned data

### ISSUE THREAD

**Issue by fana605** [jimdoescode/CodeIgniter-YouTube-API-Library#15]
Hi,
I'm using direct upload and it works fine but I don't know what to do with the returned data.
I'm getting this: tag:youtube.com,2008:video:OYUr2cdSpIs2013-01-17T18:18:43.000Z2013-01-17T18:18:43.000Z2013-01-17T18:18:43.000Zyesvelcrodesignhttp://gdata.youtube.com/feeds/api/users/velcrodesigndjjAQJa310ymM8ho0rAT6wPeoplevelcrodesignTest Direct Uploading.testyoutubeTÃƒÂ­tulo do vÃƒÂ­deo2013-01-17T18:18:43.000ZUCdjjAQJa310ymM8ho0rAT6wOYUr2cdSpIs

How can I get only the video ID?

Thanks

**Comment by jimdoescode** [comment]
YouTube responses are in XML by default. If you want the video ID you need to parse the XML and retrieve it. Some library methods will allow you to alter the response type which might make it easier to parse. However directUpload does not allow you to change the response type so you are stuck with XML.
