### ISSUE TITLE
directUpload Example

### ISSUE THREAD

**Issue by reza56** [jimdoescode/CodeIgniter-YouTube-API-Library#7]
Is there any easy example of directUpload method?
Thanks

**Comment by jimdoescode** [comment]
I update the controller example to show how a direct upload might be performed. You will need to add the relative path to the video and the content type of the video. Make sure you are using the latest version of the library as there was a bug in previous releases that was causing directUpload to fail.

**Comment by reza56** [comment]
Thank you. I see the example right now.

**Comment by cristopheribacache** [comment]
i can´t use  direct upload with codeigniter
